//import React from 'react';

//First version of API
/* export const initialData = [
  {id: 0, type: 'Banner', armedia1: 'v2.com/1', armedia2: 'v2.com/12', 
        twodtarget:'v2.com/13', turnleft:'v2.com/14', turnright:'v2.com/15', latitude:'45', longitude:'110'}, 
  {id: 1, type: 'Banner', armedia1: 'v2.com/2', armedia2: 'v2.com/22', 
        twodtarget:'v2.com/23', turnleft:'v2.com/24', turnright:'v2.com/25', latitude:'45', longitude:'110'},  
  {id: 2, type: 'Banner', armedia1: 'v2.com/3', armedia2: 'v2.com/32', 
        twodtarget:'v2.com/33', turnleft:'v2.com/34', turnright:'v2.com/35', latitude:'45', longitude:'110'}, 
  {id: 3, type: 'Un Boxing', armedia1: 'v2.com/4', armedia2: 'v2.com/42', 
        twodtarget:'v2.com/43', turnleft:'v2.com/44', turnright:'v2.com/45', latitude:'45', longitude:'110'}, 
  {id: 4, type: 'No Banner', armedia1: 'v2.com/5', armedia2: 'v2.com/52', 
        twodtarget:'v2.com/53', turnleft:'v2.com/54', turnright:'v2.com/55', latitude:'45', longitude:'110'}, 
]; */

//Second version of API
export const initialData = [
        {id: 0, type: 'Banner', 
                armedia1: { value:'v2.com/1', edit: false, validationType: 'url' }, 
                armedia2: { value:'v2.com/12', edit:true, validationType: 'url' },  
                twodtarget: { value:'v2.com/13', edit:true, validationType: 'url' },
                turnleft: { value:'v2.com/14', edit:false, validationType: 'url' }, 
                turnright: { value:'v2.com/15', edit:true, validationType: 'url' }, 
                latitude: { value:'45', edit:true, validationType: 'latitude' },
                longitude: { value:'100', edit:true, validationType: 'longitude' },
        }, 
        {id: 1, type: 'Un Boxing', 
                armedia1: { value:'v2.com/2', edit:true, validationType: 'url' }, 
                armedia2: { value:'v2.com/22', edit:false, validationType: 'url' }, 
                twodtarget: { value:'v2.com/23', edit:false, validationType: 'url' },
                turnleft: { value:'v2.com/24', edit:true, validationType: 'url' }, 
                turnright: { value:'v2.com/25', edit:true, validationType: 'url' },
                latitude: { value:'55', edit:true, validationType: 'latitude' },
                longitude: { value:'110', edit:true, validationType: 'longitude' },
        }, 
        {id: 2, type: 'Banner', 
                armedia1: { value:'v2.com/3', edit:true, validationType: 'url' }, 
                armedia2: { value:'v2.com/32', edit:true, validationType: 'url' },  
                twodtarget: { value:'v2.com/33', edit:true, validationType: 'url' },
                turnleft: { value:'v2.com/34', edit:true, validationType: 'url' }, 
                turnright: { value:'v2.com/35', edit:true, validationType: 'url' }, 
                latitude: { value:'65', edit:true, validationType: 'latitude' },
                longitude: { value:'120', edit:true, validationType: 'longitude' },
        },
        {id: 3, type: 'Banner', 
                armedia1: { value:'v2.com/4', edit:true, validationType: 'url' },
                armedia2: { value:'v2.com/42', edit:true, validationType: 'url' },
                twodtarget: { value:'v2.com/43', edit:true, validationType: 'url' },
                turnleft: { value:'v2.com/44', edit:true, validationType: 'url' },
                turnright: { value:'v2.com/35', edit:true, validationType: 'url' }, 
                latitude: { value:'75', edit:true, validationType: 'latitude' },
                longitude: { value:'130', edit:true, validationType: 'longitude' }, 
        },
        {id: 4, type: 'No Banner', 
                armedia1: { value:'v2.com/5', edit:true, validationType: 'url' }, 
                armedia2: { value:'v2.com/52', edit:true, validationType: 'url' }, 
                twodtarget: { value:'v2.com/53', edit:true, validationType: 'url' },
                turnleft: { value:'v2.com/54', edit:true, validationType: 'url' },
                turnright: { value:'v2.com/55', edit:true, validationType: 'url' },
                latitude: { value:'85', edit:true, validationType: 'latitude' },
                longitude: { value:'140', edit:true, validationType: 'longitude' }, 
        } 
     ];